WIPACrepo/lta

lta/__init__.py, setup.py, setupenv.sh
Some setup scripts we borrowed from IceProd and Authorlist, tweaked for LTA.
=> Project setup scripts

CHANGELOG.md, README.md, lta/__init__.py, lta/square.py, requirements.txt, setup.cfg, snake, tests/test_square.py
Project structure work
- CHANGELOG.md to track changes
- Documentation on establishing a development environment
- Dependency tracking in requirements.txt
- Tool configuration in setup.cfg
- Helper script `snake` to perform project tasks
- Some example source (`square.py`) and test (`test_square.py`) files , for demonstration purposes
=> Release v0.0.2

lta/config.py, lta/rest_server.py, setupenv.sh, snake, tests/test_rest_server.py
Basic rest api infrastructure.
=> Rest api infra

README.md, loglens, lta/log_format.py, lta/picker.py, tests/test_log_format.py
Adds a lens script to make console debugging easier with components that output structured log messages.
=> Console lens for structured logging

lta/rest_server.py, setup.cfg, tests/test_rest_server.py
This should be good enough to start working on the monitoring, but will obviously get revised over time.
=> basic status handling

lta/monitoring.py, requirements.txt, setupenv.sh, tests/test_monitoring.py
Only prometheus output for now, but it's nice and testable that way.
=> monitoring module with prometheus output

lta/rest_server.py, tests/test_monitoring.py, tests/test_rest_server.py
Everything except `/Files/actions/pop`
=> Implements most of the Files routes for the LTA DB

.circleci/config.yml, lta/rest_server.py, requirements.txt, tests/test_rest_server.py
I didn't fix up any of @blinkdog's scripts, because I didn't want to go down that rabbit hole.  This was only a 3 point card.
=> use fake token service in tests

lta/lta_cmd.py, lta/rest_server.py, resources/make_token.py, tests/test_rest_server.py
Modified lta_cmd.py to POST the correct body to the LTA DB
Modified the LTA DB to build the TransferRequest object correctly
Adjusted the make_token.py helper script to generate scoped roles
Updated the tests for the LTA DB
=> Refactored command: ltacmd request new

doc/transfer.md, lta/bundler.py, lta/component.py, lta/deleter.py, lta/replicator.py, lta/transfer/copy.py, lta/transfer/move.py, lta/transfer/rucio.py, lta/transfer/service.py, requirements.txt, tests/test_deleter.py, tests/test_replicator.py
Still needs:
- Unit tests for Deleter component
- Some refactoring of RucioTransferService
=> First pass at Deleter refactoring

CHANGELOG.md, lta/__init__.py, lta/rest_server.py, requirements.txt
Updated rest server routes to include admin role
=> REST server routes include admin role

CHANGELOG.md, lta/__init__.py
Bumped version and modified ChangeLog
=> Release v0.0.16

CHANGELOG.md, lta/__init__.py, lta/rest_server.py, requirements.txt, tests/test_rest_server.py
https://wipacit.atlassian.net/browse/DEV-785
=> Create convenience count route

CHANGELOG.md, lta/__init__.py, lta/site_move_verifier.py, tests/test_site_move_verifier.py
=> SiteMoveVerifier unclaimed bundles not ready for verification

CHANGELOG.md, lta/__init__.py, lta/lta_cmd.py, lta/replicator.py, lta/transfer/rucio.py, lta/transfer/service.py, requirements.txt, tests/test_replicator.py
* Rucio request logging for Replicator Debugging
=> Release v0.2.1

CHANGELOG.md, lta/__init__.py, lta/locator.py, lta/lta_cmd.py, lta/picker.py, tests/test_locator.py, tests/test_picker.py
Do paging so we can find more than 10k results, if we have a bunch of tiny files.
=> do paging on file catalog searches

CHANGELOG.md, lta/__init__.py, lta/desy_verifier.py, requirements.txt, tests/test_desy_verifier.py
* Uses `globus-url-copy` to copy the file from DESY to a work directory at WIPAC
* Runs a sha512 checksum on the file in the work directory
* If the checksums match, a record is added to the File Catalog for the bundle itself
* If the checksums match, the records for the files contained in the bundle are updated in the File Catalog
=> Adds new module DesyVerifier

CHANGELOG.md, lta/__init__.py
Should have done this with #153 ... oops :smile:
=> Bump to v0.32

lta/rest_server.py, requirements.txt
=> Bumped rest-tools dependency to v1.1.22

lta/bundler.py, lta/component.py, lta/deleter.py, lta/desy_move_verifier.py, lta/desy_stager.py, lta/desy_verifier.py, lta/gridftp_replicator.py, lta/locator.py, lta/lta_cmd.py, lta/monitoring.py, lta/nersc_mover.py, lta/nersc_retriever.py, lta/nersc_verifier.py, lta/picker.py, lta/rate_limiter.py, lta/rest_server.py, lta/site_move_verifier.py, lta/transfer/globus.py, lta/transfer_request_finisher.py, lta/unpacker.py, requirements.txt, setup.cfg
=> Bumped rest-tools dependency to v1.1.23

lta/rate_limiter.py, requirements.txt, tests/test_rate_limiter.py
Will help to clarify the root cause of #222
=> More logging for rate_limiter

bin/desy-move-verifier.sh, requirements-dev.txt, requirements.txt, resources/nersc_controller.py
* Removed some HEARTBEAT environment variables that are no longer used
* Added a logging statement to the NERSC controller script to warn about external jobs
=> Small changes that didn't make the last commit

docker-deps-down.sh, docker-deps-up.sh, lta/rest_server.py, requirements-dev.txt, requirements-monitoring.txt, requirements.txt, setup.cfg, tests/test_rest_server.py
Fixes server not responding to requests error in prod.
=> update to more modern tornado asyncio wait syntax

.github/workflows/docker.yml, requirements-dev.txt, requirements-monitoring.txt, requirements.txt
Switch from dockerhub to ghcr.io
=> use github container registry

lta/transfer/sync.py, resources/osg-certs/Dockerfile, resources/osg-certs/build-osg-cert-image, resources/osg-certs/install-osg-certs, resources/osg-certs/remove-osg-certs, resources/upload-to-desy.sh, resources/upload_to_desy.py
Some tools to:
- Install OSG certs on Debian family, by way of an AlmaLinux 9 container
- Test uploading files to DESY
=> Debug DESY Uploads Tools

Dockerfile, lta/rest_server.py, tools/outdated.py, tools/suru
=> Add suru script for CI integration
