WIPACrepo/lta

lta/config.py
lta/log_format.py
lta/picker.py
lta/square.py
requirements.txt
tests/__init__.py
tests/test_config.py
tests/test_log_format.py
tests/test_picker.py
tests/test_square.py

Used `pip install flake8-docstrings` to add docstring linting to flake8.
Fixed up the issues that it identified, except in the rest files, so as to avoid nasty merge conflicts with files that are probably being heavily modified by David right now.

Add docstring linting to the project

---

examples/rucio.json
lta/deleter.py
lta/site_move_verifier.py
lta/site_verifier.py
lta/transfer/rucio.py
requirements.txt
resources/rucio_workbench.py
rucio-workbench.sh
tests/test_site_move_verifier.py

First draft at the core logic of the component. A few points:
- `NEXT_STATUS` is a configuration variable that depends on the site. For NERSC this status will be `taping` (i.e.: next step is to issue an hpss command to move it to tape). For DESY this status will be `verifying` (i.e.: next step is to copy the file to its final destination and verify the final destination checksum)
- A checksum mismatch causes the Bundle to be quarantined. If Rucio thinks it finished transferring the file, but the sha512 checksum doesn't match, this is operator intervention territory.
Work still to be done:
Ready for initial review.

Creates SiteMoveVerifier module

---

CHANGELOG.md
lta/__init__.py
lta/bundler.py
lta/deleter.py
lta/locator.py
lta/nersc_mover.py
lta/nersc_retriever.py
lta/nersc_verifier.py
lta/picker.py
lta/replicator.py
lta/rucio_detacher.py
lta/rucio_stager.py
lta/site_move_verifier.py
lta/transfer_request_finisher.py
requirements.txt
tests/test_locator.py
tests/test_picker.py
tests/test_site_move_verifier.py
tests/test_transfer_request_finisher.py

* When components quarantine a bundle, they now add their identification (component name and UUID) to the reason message
* Quarantine reason messaging improved in several components, especially those interacting with HPSS
* When components successfully process a bundle, they remove (set to `""`) any old quarantine reason message
* A few components had `_quarantine_bundle` handlers added to them

Improve quarantine bundle reason messages

---

CHANGELOG.md
lta/__init__.py
lta/unpacker.py
tests/test_unpacker.py

When the Unpacker is unpacking files, update the correct file with the correct location in the File Catalog.

Fix Unpacker location update in File Catalog

---

CHANGELOG.md
bin/rate-limiter.sh
lta/__init__.py
lta/rate_limiter.py
tests/test_rate_limiter.py

RucioStager is now RateLimiter with more generic configuration variables:
`INPUT_PATH`: Directory where bundle files are moved from
`OUTPUT_PATH`: Directory where bundle files are moved to
`OUTPUT_QUOTA`: Limit on total size of output directory
Closes #169

Retool RucioStager as RateLimiter

---

lta/lta_cmd.py
requirements.txt

`ltacmd catalog stats` dumps records on bundles archived at NERSC.
This is important as every 6 months(ish), Benedikt needs some data/plot for reporting.
In the future, we'd probably like some dashboard that has an up-to-the-minute graph.
But for now, this command gave me what I needed for the latest report.

Add command: ltacmd catalog stats

---

lta/desy_verifier.py
lta/nersc_verifier.py
requirements.txt

Modifies DesyVerifier and NerscVerifier to add a `lta.date_archived` field to the File Catalog record for bundle files stored at DESY/NERSC.
Closes #203

Adds lta.date_archived field to bundle records in File Catalog

---

requirements.txt

`TypedDict` is not available in Python 3.6, which is currently available at NERSC.
ImportError: cannot import name 'TypedDict'
@ric-evans fixed up the dependency in wipac-telemetry:
https://github.com/WIPACrepo/wipac-telemetry-prototype/pull/33
Then bumped to that version in rest-tools:
https://github.com/WIPACrepo/rest-tools/pull/39
This PR bumps LTA to the newest version of rest-tools, which should make LTA usable at NERSC again.

Bump rest_tools dependency to v0.1.14

---

lta/lta_cmd.py
lta/rest_server.py
requirements.txt

Simplifies the GET /Metadata query by removing an `$exists` filter and a sort.
This also fixes up a bug where using ltacmd to list a Metadata entity by UUID (`ltacmd metadata ls --uuid UUID`) would DELETE the entity instead of listing it!
Closes #214

Clean up GET /Metadata query

---

tests/test_bundler.py
tests/test_component.py
tests/test_deleter.py
tests/test_desy_move_verifier.py
tests/test_desy_verifier.py
tests/test_locator.py
tests/test_monitoring.py
tests/test_nersc_mover.py
tests/test_nersc_retriever.py
tests/test_nersc_verifier.py
tests/test_picker.py
tests/test_rate_limiter.py
tests/test_rest_server.py
tests/test_site_move_verifier.py
tests/test_transfer_request_finisher.py
tests/test_unpacker.py
tests/test_util.py

As discussed with David and Ric on Slack the other day, there are a few warnings we can trim down in the tests.
`AsyncMockMixin._execute_mock_call` is a bit more tricky.
https://bugs.python.org/issue40406
This PR also replaces a home-rolled `AsyncMock` with the official `AsyncMock` from Python 3.8

Trim down some async warnings

---

README.md
lta/rate_limiter.py
requirements.txt
tests/test_rate_limiter.py

This modifies the rate-limiter component to retry when bundles in the destination directory are removed when the rate-limiter is in the middle of counting and sizing the files in the destination directory.
Fixes #222

Allow rate-limiter to ignore missing bundles in the destination check

---

lta/lta_cmd.py
requirements.txt

* Lowers regular minimum size from 100 GiB to 75 GB.
* Adds a check that transfer requests containing 0 files and/or 0 bytes cannot be archived (even with `--force`)

Modify parameters for small transfer requests

---

lta/transfer/globus.py
lta/transfer/gridftp.py

It can't find the credentials yet, so we add a `-debug` flag to the command to get more information.
```text
2023-05-15 21:18:18,334 [ThreadPoolExecutor-3_0] DEBUG (connectionpool.py:546) - https://lta.icecube.aq:443 "POST /Bundles/actions/pop?source=WIPAC&dest=NERSC&status=staged HTTP/1.1" 200 880
2023-05-15 21:18:18,335 [MainThread] INFO  (gridftp_replicator.py:106) - LTA DB responded with: {'bundle': {'type': 'Bundle', 'status': 'staged', 'reason': '', 'request': '2ef5a210eed711edb24ec24a9890dca8', 'source': 'WIPAC', 'dest': 'NERSC', 'path': '/data/exp/IceCube/2022/unbiased/PFRaw/0714', 'file_count': 66, 'uuid': '4df86e36eed711edb24ec24a9890dca8', 'create_timestamp': '2023-05-10T02:06:41', 'update_timestamp': '2023-05-15T21:18:18', 'work_priority_timestamp': '2023-05-15T21:14:21', …
```

Add -debug flag to grid-proxy-init

---

bin/deleter-nersc-return.sh
bin/gridftp-replicator.sh
bin/nersc-retriever.sh
bin/pipe0-gridftp-replicator.sh
bin/pipe0-nersc-deleter.sh
bin/pipe0-nersc-mover.sh
bin/pipe0-site-move-verifier.sh

NERSC is retiring the Cori system, including the Cori Scratch file system that lived at `/global/cscratch1/sd/icecubed`
This has been replaced by Perlmutter Scratch:
https://docs.nersc.gov/filesystems/perlmutter-scratch/
And according to NERSC, this currently lives at:
```
icecubed@perlmutter:login05:~> echo $PSCRATCH
/pscratch/sd/i/icecubed
```
This updates the configuration of LTA scripts to reflect the new scratch space.

Update LTA configuration to use Perlmutter Scratch instead of Cori Scratch

---

bin/deleter-nersc-return.sh
bin/gridftp-replicator.sh
bin/nersc-retriever.sh
bin/pipe0-gridftp-replicator.sh
bin/pipe0-nersc-deleter.sh
bin/pipe0-nersc-mover.sh
bin/pipe0-site-move-verifier.sh
requirements-dev.txt
requirements.txt

Because Cori is being retired, #250 seemed like a natural fix.
However, Perlmutter Scratch (`pscratch`) isn't mounted on the Data Transfer Nodes (DTNs) the way Cori Scratch was.
So now we use the file system that both the DTNs and Perlmutter can see.

Update LTA configuration to use Community File System instead of Perlmutter Scratch

---

bin/pipe0-nersc-verifier.sh

LTA can access the File Catalog with its own client secret.

LTA should use the long-term-archive client secret

---

nersc/scrontab
requirements-dev.txt
requirements.txt
resources/nersc-controller.sh
resources/nersc_controller.py

NERSC is 7 hours behind UTC:
```
icecubed@perlmutter:login07:~/lta/slurm-logs> date --utc
Fri 26 May 2023 10:38:12 PM UTC
icecubed@perlmutter:login07:~/lta/slurm-logs> date
Fri 26 May 2023 03:38:24 PM PDT
```
When running a nersc-mover (the LTA component that puts zip bundles on tape in HPSS), we started at 14:31 (local time) and the job is killed at 21:41 (utc time) --> 14:41 (local time):
```
2023-05-26 14:31:14,323 [MainThread] INFO  (component.py:93) - nersc_mover 'login28-pipe0-nersc-mover' is configured:
...
slurmstepd: error: *** JOB 9608169 ON login28 CANCELLED AT 2023-05-26T21:41:22 DUE TO TIME LIMIT ***
```
This means our job was cancelled after 10 minutes. This is not going to work for processes that can take a long time, like running a checksum on 100GB or copying 100GB into …

Request minimum and maximum time for slurm jobs at NERSC

---

lta/bundler.py
requirements-dev.txt
requirements.txt

In practice, one of the trickiest bits of automatically recovering quarantined bundles is that the broken files (metadata and zip bundle) still exist on the disk.
When the next attempt comes along, it will fail again, as it refuses to overwrite existing files.
Cleaning these up in case of exception would be nice, but we can't guarantee the process won't be killed (i.e. kubernetes destroys the pod) so we have to handle the 'broken files left in the work directory' case no matter what.
An external cleaner runs into two issues:
- One, how do I know when I can remove the files? Did the process die, or is it just taking a long time?
- Two, permissions; getting the permissions of the cleaner to match the permissions of the bundler isn't always easy.
So the straightforward solution is: Delete …

Bundler removes broken files of previous attempts

---

nersc/scrontab
requirements-dev.txt
requirements-monitoring.txt
requirements.txt
setup.cfg

`cd /global/homes/i/icecubed/lta/slurm-logs; find . -type f -mtime 7 -delete`
Not the most brilliant construction. If `/global/homes/i/icecubed/lta/slurm-logs` doesn't exist or is somehow inaccessible, it deletes things exactly a week old wherever scrontab jobs happen to start ... is that `${HOME}`? No idea.
Replaced with:
`find /global/homes/i/icecubed/lta/slurm-logs -type f -mtime +7 -delete`
This will find in the provided directory, or fail, and the `+7` means we get all the logs one week and older, not just those exactly a week old.

Update scrontab for prune slurm logs

---

collabssh
setup.cfg

* Modifies `collabssh` so that it invokes `sshproxy.sh` without requiring that the current directory be on one's PATH.
* Adds a lower bound on the `wipac-rest-tools` requirement; use of `ArgumentHandler` requires >=1.6.0
* Pip was choosing from the 1.5.x series, which will no longer work.

Fix Paths and Pins

---

requirements-dev.txt
requirements-monitoring.txt
requirements.txt
resources/progress_to_es.py
setupenv.sh

The syntax was written against a newer version of elasticsearch than we are using.  Go back to the older syntax.

fix monitoring script syntax

---

requirements-dev.txt
requirements-monitoring.txt
requirements.txt
resources/progress_to_es.py

The progress dump to elasticsearch job in kubernetes was failing due missing some env vars for the token creation. This change should fix taht.

Elasticsearch token url

---

.github/workflows/wipac_cicd.yml

During #283 @alemsh pointed out some failing CI workflows.
Turns out, the newest version of PyMongo requires MongoDB v4+.
The instance of MongoDB backing LTA is currently running 4.2:
```
spec:
containers:
- name: {{ .Values.spec.name }}-mongo
image: bitnami/mongodb:4.2
```
So this PR removes 3.6 and 4.0 from the strategy matrix of the CI workflow.
It's very unlikely that we'll decide to downgrade MongoDB to an older (and now incompatible) version, so we'll stop testing against them.
This should make our CI checks happy for awhile.

Remove old MongoDB versions from CI workflow

---

requirements-dev.txt
requirements-monitoring.txt
requirements.txt
resources/nersc_controller.py

At NERSC, they use the SLURM system to schedule workflows on their compute nodes.
LTA uses an `scrontab` script to specify that a controller script (`nersc_controller.py`) be run on a regular basis.
This controller script in turn queries the SLURM job system to determine how many LTA components are currently running (or scheduled to be run) at NERSC.
If more components are needed to perform work, the controller script will run the `sbatch` command to create a new job in the workflow queue.
Until the NERSC maintenance on 2025-03-26, these `sbatch` commands were executing correctly, adding jobs to the queue, and LTA was working properly.
After the maintenance was complete and the systems came back, the `sbatch` command started returning errors:
```text
2025-03-27 12:15:09,040 [MainThread] …
```

Add architecture request to sbatch call in NERSC controller

---

lta/transfer/sync.py

Got an error trying to replicate a bundle:
```
2025-08-11 18:38:31,292 [MainThread] ERROR (desy_mirror_replicator.py:155) - DESY Sync raised an Exception: unsetopt() is not supported for this option
```
There are only two `unsetopt()` calls and it relates to the file size. In my case, the bundle is 78645938923 bytes (78.6 GB) which is larger than the 2000000000 bytes (2 GB) that will trigger the path using the `unsetopt()` call.
It looks like pycurl doesn't like us calling unsetopt on that option (`INFILESIZE`). So we'll just call setopt() on the one we want (`INFILESIZE_LARGE`) see if that works.
The split between INFILESIZE and INFILESIZE_LARGE looks like a type issue in libcurl. My guess is (signed) `long` on a 32-bit system goes up to 2147483647 (2.1 GB), beyond that you're looking at …

Comment out unsetopt calls for setup_curl

---

lta/desy_mirror_replicator.py
lta/transfer/sync.py
resources/make_lta_token.py
resources/webdav_proxy.py
tests/test_desy_mirror_replicator.py
tests/test_transfer_sync.py

Just a small cleanup for how timeouts propagate downstream:
- Stops the lower level Sync class from reaching up to the config for a timeout value
- Makes the higher level DESY Mirror Replicator explicitly pass the config'd timeout value
The alternative size-based timeout minimum is hard-coded and not really documented except in the code.
It does show up in the logs, so I'll cut bait and leave it here instead of clogging up the config with more things to understand.

Refactor work timeout in DESY Mirror Replicator
